// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcW22LO_P3E1wxJRxJquFuH6mrMe13eW8',
    appId: '1:411091987638:web:1f04b03d7d9f7435be0a17',
    messagingSenderId: '411091987638',
    projectId: 'app-ventas-d67a5',
    authDomain: 'app-ventas-d67a5.firebaseapp.com',
    storageBucket: 'app-ventas-d67a5.firebasestorage.app',
    measurementId: 'G-BZP45PE8NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6af1iUbTCvqlF-UG2alETe96L3bKCVNA',
    appId: '1:411091987638:android:89c7e5691d25139fbe0a17',
    messagingSenderId: '411091987638',
    projectId: 'app-ventas-d67a5',
    storageBucket: 'app-ventas-d67a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS9myrTObP36F5PBo0O-PZfdlfvgCoQ68',
    appId: '1:411091987638:ios:a36abd742331cdb4be0a17',
    messagingSenderId: '411091987638',
    projectId: 'app-ventas-d67a5',
    storageBucket: 'app-ventas-d67a5.firebasestorage.app',
    iosBundleId: 'com.example.appVentas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS9myrTObP36F5PBo0O-PZfdlfvgCoQ68',
    appId: '1:411091987638:ios:a36abd742331cdb4be0a17',
    messagingSenderId: '411091987638',
    projectId: 'app-ventas-d67a5',
    storageBucket: 'app-ventas-d67a5.firebasestorage.app',
    iosBundleId: 'com.example.appVentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcW22LO_P3E1wxJRxJquFuH6mrMe13eW8',
    appId: '1:411091987638:web:4c59d17616a16376be0a17',
    messagingSenderId: '411091987638',
    projectId: 'app-ventas-d67a5',
    authDomain: 'app-ventas-d67a5.firebaseapp.com',
    storageBucket: 'app-ventas-d67a5.firebasestorage.app',
    measurementId: 'G-9Z9K89L932',
  );
}
